# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gererActions.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogGererActions(object):
    def setupUi(self, DialogGererActions):
        DialogGererActions.setObjectName("DialogGererActions")
        DialogGererActions.resize(578, 505)
        DialogGererActions.setMinimumSize(QtCore.QSize(578, 505))
        DialogGererActions.setMaximumSize(QtCore.QSize(578, 505))
        DialogGererActions.setSizeGripEnabled(True)
        DialogGererActions.setModal(True)
        self.listeEtape = QtWidgets.QListView(DialogGererActions)
        self.listeEtape.setGeometry(QtCore.QRect(90, 20, 471, 261))
        self.listeEtape.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listeEtape.setWordWrap(True)
        self.listeEtape.setObjectName("listeEtape")
        self.horizontalLayoutWidget = QtWidgets.QWidget(DialogGererActions)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(13, 281, 551, 181))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.layoutEtape = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.layoutEtape.setContentsMargins(0, 0, 0, 0)
        self.layoutEtape.setObjectName("layoutEtape")
        self.layoutSaisie = QtWidgets.QFormLayout()
        self.layoutSaisie.setObjectName("layoutSaisie")
        self.labelOrdre = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelOrdre.setObjectName("labelOrdre")
        self.layoutSaisie.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelOrdre)
        self.textOrdre = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.textOrdre.setObjectName("textOrdre")
        self.layoutSaisie.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textOrdre)
        self.labelEtape = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelEtape.setObjectName("labelEtape")
        self.layoutSaisie.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelEtape)
        self.textEtape = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textEtape.setObjectName("textEtape")
        self.layoutSaisie.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textEtape)
        self.inputDate = QtWidgets.QDateTimeEdit(self.horizontalLayoutWidget)
        self.inputDate.setCalendarPopup(True)
        self.inputDate.setObjectName("inputDate")
        self.layoutSaisie.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.inputDate)
        self.buttonAjouterModifier = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.buttonAjouterModifier.setObjectName("buttonAjouterModifier")
        self.layoutSaisie.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.buttonAjouterModifier)
        self.checkBoxDate = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBoxDate.setObjectName("checkBoxDate")
        self.layoutSaisie.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBoxDate)
        self.labelDate = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelDate.setObjectName("labelDate")
        self.layoutSaisie.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelDate)
        self.layoutEtape.addLayout(self.layoutSaisie)
        self.verticalFait = QtWidgets.QVBoxLayout()
        self.verticalFait.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalFait.setContentsMargins(0, -1, -1, -1)
        self.verticalFait.setObjectName("verticalFait")
        self.horizontalLayoutFait = QtWidgets.QHBoxLayout()
        self.horizontalLayoutFait.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayoutFait.setObjectName("horizontalLayoutFait")
        self.labelFait = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelFait.setObjectName("labelFait")
        self.horizontalLayoutFait.addWidget(self.labelFait)
        self.labelFaitValue = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelFaitValue.setFont(font)
        self.labelFaitValue.setObjectName("labelFaitValue")
        self.horizontalLayoutFait.addWidget(self.labelFaitValue)
        self.verticalFait.addLayout(self.horizontalLayoutFait)
        self.buttonChangerEtat = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.buttonChangerEtat.setObjectName("buttonChangerEtat")
        self.verticalFait.addWidget(self.buttonChangerEtat)
        self.layoutEtape.addLayout(self.verticalFait)
        self.buttonDialog = QtWidgets.QDialogButtonBox(DialogGererActions)
        self.buttonDialog.setGeometry(QtCore.QRect(13, 468, 551, 31))
        self.buttonDialog.setOrientation(QtCore.Qt.Horizontal)
        self.buttonDialog.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonDialog.setObjectName("buttonDialog")
        self.buttonMonter = QtWidgets.QPushButton(DialogGererActions)
        self.buttonMonter.setGeometry(QtCore.QRect(10, 20, 71, 23))
        self.buttonMonter.setObjectName("buttonMonter")
        self.buttonDescendre = QtWidgets.QPushButton(DialogGererActions)
        self.buttonDescendre.setGeometry(QtCore.QRect(10, 80, 71, 23))
        self.buttonDescendre.setObjectName("buttonDescendre")
        self.buttonSupprimer = QtWidgets.QPushButton(DialogGererActions)
        self.buttonSupprimer.setGeometry(QtCore.QRect(10, 50, 71, 23))
        self.buttonSupprimer.setObjectName("buttonSupprimer")

        self.retranslateUi(DialogGererActions)
        self.buttonDialog.accepted.connect(DialogGererActions.accept)
        self.buttonDialog.rejected.connect(DialogGererActions.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogGererActions)

    def retranslateUi(self, DialogGererActions):
        _translate = QtCore.QCoreApplication.translate
        DialogGererActions.setWindowTitle(_translate("DialogGererActions", "Gérer les étapes"))
        self.labelOrdre.setText(_translate("DialogGererActions", "Ordre"))
        self.labelEtape.setText(_translate("DialogGererActions", "Etape"))
        self.buttonAjouterModifier.setText(_translate("DialogGererActions", "Editer"))
        self.checkBoxDate.setText(_translate("DialogGererActions", "Rajouter une date d\'éxécution"))
        self.labelDate.setText(_translate("DialogGererActions", "Date"))
        self.labelFait.setText(_translate("DialogGererActions", "Etat : "))
        self.labelFaitValue.setText(_translate("DialogGererActions", "A faire"))
        self.buttonChangerEtat.setText(_translate("DialogGererActions", "Inverser l\'état"))
        self.buttonMonter.setText(_translate("DialogGererActions", "Monter"))
        self.buttonDescendre.setText(_translate("DialogGererActions", "Descendre"))
        self.buttonSupprimer.setText(_translate("DialogGererActions", "Supprimer"))

